[tool.poetry]
name = "sso-elevator"
version = "0.1.0"
description = ""
authors = ["EreminAnton <mobessona2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.16"
boto3-stubs = {extras = ["dynamodb", "organizations", "sso-admin", "identitystore"], version = "^1.26.99"}
boto3 = "^1.26.97"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
black = "^23.1.0"

# from lambda layers
pydantic = "^1.10.7"
aws-lambda-powertools = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 140

[tool.ruff]
line-length = 140

