name: CodeGuru Review

on:
  push:
    branches: [ "*" ]
on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the repository and provide your AWS credentials
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1 
          role-to-assume: ${{ secrets.DEVELOPMENT_ACCOUNT_ROLE_ARN }}
          role-duration-seconds: 3600
          role-session-name: ${{ github.event.repository.name }}
      
      # Step 2: Add CodeGuru Reviewer Action
      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: codeguru-reviewer-mambo-jumbo
       
      # Step 3: Upload results into GitHub
      - name: Upload review result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-results.sarif.json
